apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  KC_DB_PASSWORD: "keycloak"  # Change this!
  KEYCLOAK_ADMIN_PASSWORD: "admin123"  # Change this!
  POSTGRES_PASSWORD: "postgres123"  # Change this!
